from __future__ import annotations

import json
import threading
import zipfile
from collections.abc import Mapping
from io import BytesIO
from pathlib import Path
from typing import Any

import pytest

from agent_insights_quality.contracts import ROOT
from agent_insights_quality.agent_runtime import (
    DIGEST_KEY,
    HOSTED_FEATURES,
    IMAGE_DIGEST_KEY,
    OWNER_KEY,
    OWNER_VALUE,
    RUN_KEY,
    SOURCE_DIGEST_KEY,
    DeploymentReceipt,
    DeploymentCleanupError,
    DeploymentPollError,
    FoundryDeploymentClient,
    FoundryInvocationClient,
    FoundryRequestTimeout,
    HealthyFixture,
    HttpResponse,
    InvocationEndpointError,
    InvocationFailureReceipt,
    RuntimeContractError,
    SyntheticToolOperation,
    _ENDPOINT_CASES,
    _ENDPOINT_HEALTHY_CASES,
    canonical_json_digest,
    deterministic_zip,
    load_fixtures,
    run_healthy_traffic,
    validate_image_reference,
)


PROJECT_ENDPOINT = "https://sample.services.ai.azure.com/api/projects/quality"


def _response(
    status: int,
    value: Mapping[str, Any] | None = None,
    *,
    headers: Mapping[str, str] | None = None,
) -> HttpResponse:
    return HttpResponse(
        status_code=status,
        headers=headers or {},
        body=json.dumps(value or {}, separators=(",", ":")).encode("ascii"),
    )


class QueueTransport:
    def __init__(self, responses: list[HttpResponse]) -> None:
        self.responses = list(responses)
        self.calls: list[dict[str, Any]] = []
        self.lock = threading.Lock()

    def request(self, method, url, *, headers, body, timeout_seconds):
        with self.lock:
            self.calls.append(
                {
                    "method": method,
                    "url": url,
                    "headers": dict(headers),
                    "body": body,
                    "timeout_seconds": timeout_seconds,
                }
            )
            if not self.responses:
                raise AssertionError(f"Unexpected request: {method} {url}")
            return self.responses.pop(0)


def _metadata(run_id: str, digest: str) -> dict[str, str]:
    return {OWNER_KEY: OWNER_VALUE, RUN_KEY: run_id, DIGEST_KEY: digest}


def test_definition_and_source_hashes_are_deterministic(tmp_path: Path) -> None:
    definition = {"kind": "prompt", "tools": [], "model": "synthetic"}
    assert canonical_json_digest(definition) == canonical_json_digest(
        {"model": "synthetic", "tools": [], "kind": "prompt"}
    )
    source = tmp_path / "source"
    source.mkdir()
    (source / "main.py").write_bytes(b"print('healthy')\n")
    (source / "requirements.txt").write_bytes(b"example==1.0\n")
    first, first_digest = deterministic_zip(source)
    second, second_digest = deterministic_zip(source)
    assert first == second
    assert first_digest == second_digest
    assert first_digest == "sha256:c047775d84ad57a04b790b7c1b26208196e1a6bc76a4fe558cd0ad94351359c4"
    with zipfile.ZipFile(BytesIO(first)) as archive:
        assert all(info.create_system == 3 for info in archive.infolist())


def test_deployment_zip_ignores_the_same_generated_artifacts_as_catalog_hash(
    tmp_path: Path,
) -> None:
    source = tmp_path / "source"
    reviewed = source / "main.py"
    reviewed.parent.mkdir()
    reviewed.write_text("print('reviewed')\n", encoding="ascii")
    expected, expected_digest = deterministic_zip(source)

    for path in (
        source / "__pycache__" / "main.cpython-312.pyc",
        source / "build" / "generated.py",
        source / ".scratch.json",
        source / "transient.tmp",
    ):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(b"ignored generated bytes")

    observed, observed_digest = deterministic_zip(source)
    assert observed == expected
    assert observed_digest == expected_digest

    reviewed.write_text("print('changed')\n", encoding="ascii")
    assert deterministic_zip(source)[1] != expected_digest


def test_prompt_deployment_sends_real_token_and_polls_owned_version() -> None:
    definition = {"kind": "prompt", "model": "test", "instructions": "healthy", "tools": []}
    digest = canonical_json_digest(definition)
    transport = QueueTransport(
        [
            _response(201, {"version": "7"}),
            _response(200, {"status": "active", "metadata": _metadata("run-1", digest)}),
        ]
    )
    client = FoundryDeploymentClient(
        PROJECT_ENDPOINT,
        lambda: "short-lived-token",
        transport=transport,
        sleeper=lambda _seconds: None,
    )
    receipt = client.deploy_prompt(
        agent_name="aiq-001-weather", definition=definition, run_id="run-1"
    )
    assert receipt.agent_version == "7"
    assert receipt.artifact_digest == digest
    assert transport.calls[0]["headers"]["Authorization"] == "Bearer short-lived-token"
    payload = json.loads(transport.calls[0]["body"])
    assert payload["metadata"] == _metadata("run-1", digest)
    assert payload["definition"] == definition
    assert transport.calls[1]["url"].endswith(
        "/agents/aiq-001-weather/versions/7?api-version=v1"
    )


def test_deployment_recovery_reuses_exact_owned_version_without_post() -> None:
    digest = "sha256:" + ("a" * 64)
    metadata = _metadata("run-1", digest)
    transport = QueueTransport(
        [
            _response(
                200,
                {
                    "name": "aiq-001-weather",
                    "versions": {
                        "latest": {
                            "version": "7",
                            "metadata": metadata,
                        }
                    },
                },
            ),
            _response(
                200,
                {
                    "version": "7",
                    "status": "active",
                    "metadata": metadata,
                },
            ),
        ]
    )
    client = FoundryDeploymentClient(
        PROJECT_ENDPOINT,
        lambda: "short-lived-token",
        transport=transport,
        sleeper=lambda _seconds: None,
    )
    receipt, agent_exists = client.recover_version(
        agent_name="aiq-001-weather",
        agent_type="prompt",
        run_id="run-1",
        artifact_digest=digest,
    )
    assert agent_exists is True
    assert receipt is not None
    assert receipt.agent_version == "7"
    assert [call["method"] for call in transport.calls] == ["GET", "GET"]


def test_hosted_source_uses_multipart_hash_feature_header_and_timeout() -> None:
    source = ROOT / "agents" / "finance-hosted" / "source"
    _, source_digest = deterministic_zip(source)
    definition = json.loads(
        (ROOT / "agents" / "finance-hosted" / "definition.json").read_text(
            encoding="ascii"
        )
    )
    digest = canonical_json_digest(
        {"definition": definition, "source_digest": source_digest}
    )
    active_metadata = {
        **_metadata("run-2", digest),
        SOURCE_DIGEST_KEY: source_digest,
    }
    transport = QueueTransport(
        [
            _response(201, {"version": "2"}),
            _response(200, {"status": "active", "metadata": active_metadata}),
        ]
    )
    client = FoundryDeploymentClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=transport,
        request_timeout_seconds=37,
        sleeper=lambda _seconds: None,
    )
    receipt = client.deploy_hosted_source(
        agent_name="aiq-003-finance",
        definition=definition,
        source=source,
        run_id="run-2",
    )
    call = transport.calls[0]
    assert receipt.artifact_digest == digest
    assert receipt.source_digest == source_digest
    assert call["headers"]["x-ms-code-zip-sha256"] == source_digest.removeprefix(
        "sha256:"
    )
    assert call["headers"]["Foundry-Features"] == HOSTED_FEATURES
    assert call["headers"]["Content-Type"].startswith("multipart/form-data; boundary=aiq-")
    assert b'name="metadata"' in call["body"]
    assert b'name="code"; filename="aiq-003-finance.zip"' in call["body"]
    assert call["timeout_seconds"] == 37


def test_container_deployment_requires_immutable_reviewed_registry_digest() -> None:
    image_digest = "sha256:" + ("a" * 64)
    image = f"ghcr.io/ninghu/agent-insights-quality-ticket@{image_digest}"
    definition = json.loads(
        (
            ROOT / "agents" / "support-ticket-hosted-image" / "definition.json"
        ).read_text(encoding="ascii")
    )
    resolved = json.loads(json.dumps(definition))
    resolved["container_configuration"]["image"] = image
    digest = canonical_json_digest(resolved)
    active_metadata = {
        **_metadata("run-3", digest),
        IMAGE_DIGEST_KEY: image_digest,
    }
    transport = QueueTransport(
        [
            _response(201, {"version": "3"}),
            _response(200, {"status": "active", "metadata": active_metadata}),
        ]
    )
    client = FoundryDeploymentClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=transport,
        sleeper=lambda _seconds: None,
    )
    receipt = client.deploy_hosted_container(
        agent_name="aiq-005-ticket",
        definition=definition,
        image=image,
        run_id="run-3",
    )
    payload = json.loads(transport.calls[0]["body"])
    assert receipt.artifact_digest == digest
    assert receipt.image_digest == image_digest
    assert payload["definition"]["container_configuration"]["image"] == image
    assert transport.calls[0]["headers"]["Foundry-Features"] == HOSTED_FEATURES
    assert transport.calls[0]["timeout_seconds"] == 300
    acr_image = (
        "aiqacr123.azurecr.io/agent-insights-quality-ticket@sha256:"
        + ("b" * 64)
    )
    assert validate_image_reference(acr_image) == acr_image
    with pytest.raises(RuntimeContractError, match="reviewed GHCR or Azure"):
        validate_image_reference("private.azurecr.io/ticket:latest")
    with pytest.raises(RuntimeContractError, match="reviewed GHCR or Azure"):
        validate_image_reference("ghcr.io/ninghu/agent-insights-quality-ticket:latest")
    for rejected in (
        "aiqacr123.azurecr.io/ticket@sha256:" + ("a" * 64),
        "aiq-acr.azurecr.io/agent-insights-quality-ticket@sha256:" + ("a" * 64),
        "aiqacr123.azurecr.io/agent-insights-quality-ticket:latest",
        "aiqacr123.example.com/agent-insights-quality-ticket@sha256:" + ("a" * 64),
    ):
        with pytest.raises(RuntimeContractError, match="reviewed GHCR or Azure"):
            validate_image_reference(rejected)


def test_cleanup_deletes_only_the_exact_owned_version() -> None:
    digest = "sha256:" + ("b" * 64)
    source_digest = "sha256:" + ("c" * 64)
    receipt = DeploymentReceipt(
        agent_name="aiq-004-travel",
        agent_version="9",
        agent_type="hosted_code",
        artifact_digest=digest,
        run_id="run-clean",
        status="active",
        source_digest=source_digest,
    )
    metadata = {
        **_metadata("run-clean", digest),
        SOURCE_DIGEST_KEY: source_digest,
    }
    transport = QueueTransport(
        [
            _response(200, {"metadata": metadata}),
            _response(
                200,
                {
                    "name": receipt.agent_name,
                    "version": receipt.agent_version,
                    "deleted": True,
                },
            ),
        ]
    )
    client = FoundryDeploymentClient(
        PROJECT_ENDPOINT, lambda: "token", transport=transport
    )
    cleanup = client.cleanup_version(receipt)
    assert cleanup.agent_name == receipt.agent_name
    assert cleanup.agent_version == receipt.agent_version
    assert cleanup.run_id == receipt.run_id
    assert cleanup.deleted is True
    assert transport.calls[-1]["method"] == "DELETE"
    assert "/versions/9?" in transport.calls[-1]["url"]

    mismatch = QueueTransport([_response(200, {"metadata": {}})])
    guarded = FoundryDeploymentClient(
        PROJECT_ENDPOINT, lambda: "token", transport=mismatch
    )
    with pytest.raises(RuntimeContractError, match="ownership"):
        guarded.cleanup_version(receipt)
    assert len(mismatch.calls) == 1

    unconfirmed = QueueTransport(
        [
            _response(200, {"metadata": metadata}),
            _response(
                200,
                {
                    "name": receipt.agent_name,
                    "version": receipt.agent_version,
                    "deleted": False,
                },
            ),
        ]
    )
    unchecked = FoundryDeploymentClient(
        PROJECT_ENDPOINT, lambda: "token", transport=unconfirmed
    )
    with pytest.raises(RuntimeContractError, match="did not confirm deletion"):
        unchecked.cleanup_version(receipt)


def test_hosted_cleanup_retries_active_sessions_and_remains_resumable() -> None:
    digest = "sha256:" + ("b" * 64)
    source_digest = "sha256:" + ("c" * 64)
    receipt = DeploymentReceipt(
        "aiq-004-travel",
        "9",
        "hosted_code",
        digest,
        "run-clean",
        "active",
        source_digest=source_digest,
    )
    metadata = {
        "metadata": {
            **_metadata("run-clean", digest),
            SOURCE_DIGEST_KEY: source_digest,
        }
    }
    transport = QueueTransport(
        [
            _response(200, metadata),
            *[_response(409) for _ in range(4)],
            _response(200, metadata),
            _response(
                200,
                {
                    "name": receipt.agent_name,
                    "version": receipt.agent_version,
                    "deleted": True,
                },
            ),
        ]
    )
    sleeps: list[float] = []
    client = FoundryDeploymentClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=transport,
        cleanup_retry_attempts=4,
        cleanup_retry_interval_seconds=300,
        sleeper=sleeps.append,
    )

    with pytest.raises(DeploymentCleanupError) as blocked:
        client.cleanup_version(receipt)
    assert blocked.value.code == "deployment_cleanup_sessions_active"
    assert sleeps == [300, 300, 300]

    result = client.cleanup_version(receipt)
    assert result.deleted is True
    assert sum(call["method"] == "DELETE" for call in transport.calls) == 5


def test_cleanup_resume_treats_exact_version_absence_as_completed() -> None:
    receipt = DeploymentReceipt(
        "aiq-004-travel",
        "9",
        "hosted_code",
        "sha256:" + ("b" * 64),
        "run-clean",
        "active",
        source_digest="sha256:" + ("c" * 64),
    )
    transport = QueueTransport([_response(404)])
    client = FoundryDeploymentClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=transport,
    )

    result = client.cleanup_version(receipt)

    assert result.deleted is True
    assert [call["method"] for call in transport.calls] == ["GET"]


def test_deployment_timeout_is_bounded_and_actionably_classified() -> None:
    class TimeoutTransport:
        def request(self, *_args, **kwargs):
            assert kwargs["timeout_seconds"] == 300
            raise TimeoutError("synthetic timeout")

    client = FoundryDeploymentClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=TimeoutTransport(),
    )

    with pytest.raises(FoundryRequestTimeout, match="300-second") as caught:
        client.deploy_prompt(
            agent_name="aiq-001-weather",
            definition={"kind": "prompt", "model": "test", "tools": []},
            run_id="run-timeout",
        )
    assert caught.value.code == "agent_deployment_timeout"
    assert caught.value.transient is True


def test_deployment_poll_preserves_transient_timeout_classification() -> None:
    definition = {"kind": "prompt", "model": "test", "tools": []}

    class CreateThenTimeoutTransport:
        def __init__(self) -> None:
            self.calls = 0

        def request(self, *_args, **kwargs):
            self.calls += 1
            if self.calls == 1:
                return _response(201, {"version": "1"})
            raise TimeoutError("synthetic poll timeout")

    client = FoundryDeploymentClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=CreateThenTimeoutTransport(),
    )

    with pytest.raises(DeploymentPollError) as caught:
        client.deploy_prompt(
            agent_name="aiq-001-weather",
            definition=definition,
            run_id="poll-timeout",
        )
    assert caught.value.code == "agent_deployment_timeout"
    assert caught.value.transient is True


def test_prompt_invocation_binds_exact_version_and_returns_non_trace_receipt() -> None:
    fixture = HealthyFixture(
        id="weather-current-seattle",
        input="weather",
        output_contains="partly cloudy",
        tool_outputs={
            "current_weather": {
                "arguments": {"location_id": "loc-sea"},
                "result": {"condition": "partly cloudy"},
            }
        },
        expected_tool_calls=("current_weather",),
    )
    transport = QueueTransport(
        [
            _response(
                200,
                {
                    "id": "resp-1",
                    "status": "in_progress",
                    "output": [
                        {
                            "type": "function_call",
                            "call_id": "call-1",
                            "name": "current_weather",
                            "arguments": '{"location_id":"loc-sea"}',
                        }
                    ],
                },
            ),
            _response(
                200,
                {
                    "id": "resp-2",
                    "invocation_id": "protocol-invocation-prompt-2",
                    "status": "completed",
                    "output_text": "The evidence says partly cloudy.",
                },
                headers={"x-ms-request-id": "invocation-prompt-2"},
            ),
        ]
    )
    client = FoundryInvocationClient(
        PROJECT_ENDPOINT, lambda: "runtime-token", transport=transport
    )
    receipt = client.invoke_prompt(
        DeploymentReceipt(
            "aiq-001-weather", "12", "prompt", "sha256:" + ("c" * 64), "run", "active"
        ),
        fixture,
    )
    first = json.loads(transport.calls[0]["body"])
    second = json.loads(transport.calls[1]["body"])
    assert first["agent_reference"]["version"] == "12"
    assert transport.calls[0]["url"].endswith("/openai/v1/responses")
    assert second["previous_response_id"] == "resp-1"
    assert receipt.response_id == "resp-2"
    assert receipt.invocation_id == "protocol-invocation-prompt-2"
    assert receipt.request_id == "invocation-prompt-2"
    assert receipt.called_tools == ("current_weather",)
    assert receipt.trace_id is None
    assert all(
        call["headers"]["Authorization"] == "Bearer runtime-token"
        for call in transport.calls
    )


def test_prompt_rate_limit_retries_with_conservative_default_backoff() -> None:
    fixture = HealthyFixture(
        id="weather-retry",
        input="weather",
        output_contains="ready",
        tool_outputs={},
        expected_tool_calls=(),
    )
    transport = QueueTransport(
        [
            _response(429, {"error": {"code": "rate_limit_exceeded"}}),
            _response(
                200,
                {
                    "id": "response-after-throttle",
                    "status": "completed",
                    "output_text": "ready",
                },
            ),
        ]
    )
    sleeps: list[float] = []
    client = FoundryInvocationClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=transport,
        sleeper=sleeps.append,
    )

    receipt = client.invoke_prompt(
        DeploymentReceipt(
            "aiq-001-weather",
            "12",
            "prompt",
            "sha256:" + ("c" * 64),
            "run",
            "active",
        ),
        fixture,
    )

    assert receipt.response_id == "response-after-throttle"
    assert sum(sleeps) == pytest.approx(60)
    assert all(0 < interval <= 0.1 for interval in sleeps)
    assert len(transport.calls) == 2


def test_hosted_session_rate_limit_retries_before_creating_one_session() -> None:
    fixture = HealthyFixture(
        id="finance-retry",
        input="prepare",
        output_contains="ready",
        tool_outputs={},
        expected_tool_calls=(),
    )
    transport = QueueTransport(
        [
            _response(429, {"error": {"code": "rate_limit_exceeded"}}),
            _response(
                201,
                {
                    "agent_session_id": "session-after-throttle",
                    "version_indicator": {
                        "type": "version_ref",
                        "agent_version": "8",
                    },
                },
            ),
            _response(
                200,
                {
                    "id": "response-after-throttle",
                    "status": "completed",
                    "output_text": "ready",
                },
            ),
            _response(204),
        ]
    )
    sleeps: list[float] = []
    client = FoundryInvocationClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=transport,
        sleeper=sleeps.append,
    )

    receipt = client.invoke_hosted(
        DeploymentReceipt(
            "aiq-003-finance",
            "8",
            "hosted_code",
            "sha256:" + ("d" * 64),
            "run",
            "active",
        ),
        fixture,
    )

    assert receipt.session_id == "session-after-throttle"
    assert sum(sleeps) == pytest.approx(60)
    assert all(0 < interval <= 0.1 for interval in sleeps)
    assert sum("/endpoint/sessions?" in call["url"] for call in transport.calls) == 2
    assert sum(
        "/endpoint/protocols/openai/responses?" in call["url"]
        for call in transport.calls
    ) == 1


@pytest.mark.parametrize("status", [408, 500, 502, 503, 504])
def test_pre_response_transient_status_is_preserved_without_body(
    status: int,
) -> None:
    fixture = HealthyFixture(
        id="transient-status",
        input="run",
        output_contains="unused",
        tool_outputs={},
        expected_tool_calls=(),
    )
    transport = QueueTransport(
        [
            _response(
                status,
                {"error": {"code": "private-service-detail"}},
                headers={"x-ms-request-id": "request-reference"},
            )
        ]
    )
    client = FoundryInvocationClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=transport,
        transient_retry_attempts=1,
        sleeper=lambda _seconds: None,
    )

    with pytest.raises(InvocationEndpointError) as caught:
        client.invoke_prompt(
            DeploymentReceipt(
                "aiq-001-weather",
                "12",
                "prompt",
                "sha256:" + ("c" * 64),
                "run",
                "active",
            ),
            fixture,
        )

    assert caught.value.transient is True
    assert caught.value.receipt.http_status == status
    assert caught.value.receipt.response_id is None
    assert "private-service-detail" not in str(caught.value)


def test_nontransient_bad_request_is_not_retried() -> None:
    fixture = HealthyFixture(
        id="bad-request",
        input="run",
        output_contains="unused",
        tool_outputs={},
        expected_tool_calls=(),
    )
    transport = QueueTransport(
        [_response(400, {"error": {"code": "invalid_request"}})]
    )
    sleeps: list[float] = []
    client = FoundryInvocationClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=transport,
        sleeper=sleeps.append,
    )

    with pytest.raises(InvocationEndpointError) as caught:
        client.invoke_prompt(
            DeploymentReceipt(
                "aiq-001-weather",
                "12",
                "prompt",
                "sha256:" + ("c" * 64),
                "run",
                "active",
            ),
            fixture,
        )

    assert caught.value.transient is False
    assert caught.value.receipt.http_status == 400
    assert len(transport.calls) == 1
    assert sleeps == []


def test_hosted_invocation_routes_to_endpoint_with_exact_session_binding() -> None:
    fixture = HealthyFixture(
        id="finance-budget",
        input="prepare-budget account=SYN-100 monthly_limit=1200",
        output_contains="No transfer was attempted",
        tool_outputs={},
        expected_tool_calls=(),
    )
    transport = QueueTransport(
        [
            _response(
                201,
                {
                    "agent_session_id": "session-8",
                    "version_indicator": {
                        "type": "version_ref",
                        "agent_version": "8",
                    },
                },
            ),
            _response(
                200,
                {
                    "id": "response-8",
                    "invocation_id": "protocol-invocation-hosted-8",
                    "status": "completed",
                    "output_text": "No transfer was attempted.",
                },
                headers={"x-request-id": "invocation-hosted-8"},
            ),
            _response(204),
        ]
    )
    client = FoundryInvocationClient(
        PROJECT_ENDPOINT, lambda: "token", transport=transport
    )
    receipt = client.invoke_hosted(
        DeploymentReceipt(
            "aiq-003-finance",
            "8",
            "hosted_code",
            "sha256:" + ("d" * 64),
            "run",
            "active",
        ),
        fixture,
    )
    assert transport.calls[0]["url"].endswith(
        "/agents/aiq-003-finance/endpoint/sessions?api-version=v1"
    )
    assert json.loads(transport.calls[0]["body"])["version_indicator"] == {
        "type": "version_ref",
        "agent_version": "8",
    }
    assert "/endpoint/protocols/openai/responses?api-version=v1" in transport.calls[1][
        "url"
    ]
    assert receipt.session_id == "session-8"
    assert receipt.response_id == "response-8"
    assert receipt.invocation_id == "protocol-invocation-hosted-8"
    assert receipt.request_id == "invocation-hosted-8"
    assert json.loads(transport.calls[1]["body"])["agent_session_id"] == "session-8"
    assert transport.calls[2]["method"] == "DELETE"
    assert transport.calls[2]["url"].endswith(
        "/agents/aiq-003-finance/endpoint/sessions/session-8?api-version=v1"
    )
    assert all(
        call["headers"]["Foundry-Features"] == HOSTED_FEATURES
        for call in transport.calls
    )


def test_hosted_session_version_mismatch_is_cleaned_up() -> None:
    fixture = HealthyFixture(
        id="travel-flight-search",
        input="search",
        output_contains="unused",
        tool_outputs={},
        expected_tool_calls=(),
    )
    transport = QueueTransport(
        [
            _response(
                201,
                {
                    "agent_session_id": "wrong-session",
                    "version_indicator": {
                        "type": "version_ref",
                        "agent_version": "previous",
                    },
                },
            ),
            _response(204),
        ]
    )
    client = FoundryInvocationClient(
        PROJECT_ENDPOINT, lambda: "token", transport=transport
    )
    deployment = DeploymentReceipt(
        "aiq-004-travel",
        "current",
        "hosted_code",
        "sha256:" + ("f" * 64),
        "run",
        "active",
    )
    with pytest.raises(RuntimeContractError, match="exact deployed version"):
        client.invoke_hosted(deployment, fixture)
    assert transport.calls[-1]["method"] == "DELETE"
    assert "/endpoint/sessions/wrong-session?" in transport.calls[-1]["url"]


def test_hosted_endpoint_failure_raises_invocation_endpoint_error_and_still_deletes_session() -> None:
    """HTTP 5xx after exact-version session creation raises InvocationEndpointError."""
    fixture = HealthyFixture(
        id="hosted-fail",
        input="do-work",
        output_contains="unused",
        tool_outputs={},
        expected_tool_calls=(),
    )
    transport = QueueTransport(
        [
            _response(
                201,
                {
                    "agent_session_id": "sess-fail-1",
                    "version_indicator": {"type": "version_ref", "agent_version": "v5"},
                },
            ),
            # Endpoint call returns 503 with partial body
            HttpResponse(
                status_code=503,
                headers={"x-request-id": "req-fail-42"},
                body=json.dumps({"id": "partial-resp-id"}).encode(),
            ),
            _response(204),  # session deletion
        ]
    )
    client = FoundryInvocationClient(PROJECT_ENDPOINT, lambda: "token", transport=transport)
    deployment = DeploymentReceipt(
        "aiq-005-hosted",
        "v5",
        "hosted_code",
        "sha256:" + ("b" * 64),
        "run",
        "active",
    )
    with pytest.raises(InvocationEndpointError) as exc_info:
        client.invoke_hosted(deployment, fixture)

    err = exc_info.value
    assert isinstance(err.receipt, InvocationFailureReceipt)
    assert err.receipt.http_status == 503
    assert err.receipt.agent_name == "aiq-005-hosted"
    assert err.receipt.agent_version == "v5"
    assert err.receipt.session_id == "sess-fail-1"
    assert err.receipt.request_id == "req-fail-42"
    assert err.receipt.response_id == "partial-resp-id"
    # Session must still have been deleted
    assert transport.calls[-1]["method"] == "DELETE"
    assert "/endpoint/sessions/sess-fail-1?" in transport.calls[-1]["url"]


def test_hosted_endpoint_contract_error_is_not_wrapped_in_invocation_endpoint_error() -> None:
    """A RuntimeContractError from inside the try-block (version mismatch) stays distinct."""
    fixture = HealthyFixture(
        id="contract-check",
        input="x",
        output_contains="unused",
        tool_outputs={},
        expected_tool_calls=(),
    )
    transport = QueueTransport(
        [
            _response(
                201,
                {
                    "agent_session_id": "sess-v6",
                    "version_indicator": {"type": "version_ref", "agent_version": "v-wrong"},
                },
            ),
            _response(204),
        ]
    )
    client = FoundryInvocationClient(PROJECT_ENDPOINT, lambda: "token", transport=transport)
    deployment = DeploymentReceipt(
        "aiq-006-hosted",
        "v6",
        "hosted_code",
        "sha256:" + ("c" * 64),
        "run",
        "active",
    )
    with pytest.raises(RuntimeContractError) as exc_info:
        client.invoke_hosted(deployment, fixture)
    assert not isinstance(exc_info.value, InvocationEndpointError)


def test_deployment_poll_fails_on_terminal_state_and_timeout() -> None:
    definition = {"kind": "prompt", "model": "test", "instructions": "healthy", "tools": []}
    failed_transport = QueueTransport(
        [
            _response(201, {"version": "1"}),
            _response(200, {"status": "failed", "error": {"code": "CodeError"}}),
        ]
    )
    failed = FoundryDeploymentClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=failed_transport,
        sleeper=lambda _seconds: None,
    )
    with pytest.raises(DeploymentPollError, match="CodeError") as failed_error:
        failed.deploy_prompt(
            agent_name="aiq-001-weather", definition=definition, run_id="failed"
        )
    assert failed_error.value.receipt.agent_version == "1"
    assert failed_error.value.receipt.status == "failed"

    ticks = iter((0.0, 1.0, 2.0))
    timeout_transport = QueueTransport(
        [
            _response(201, {"version": "2"}),
            _response(200, {"status": "creating"}),
        ]
    )
    timed = FoundryDeploymentClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=timeout_transport,
        poll_timeout_seconds=1,
        sleeper=lambda _seconds: None,
        monotonic=lambda: next(ticks),
    )
    with pytest.raises(DeploymentPollError, match="before timeout") as timeout_error:
        timed.deploy_prompt(
            agent_name="aiq-001-weather", definition=definition, run_id="timed"
        )
    assert timeout_error.value.receipt.agent_version == "2"
    assert timeout_error.value.receipt.status == "timeout"

    polling_transport = QueueTransport(
        [
            _response(201, {"version": "3"}),
            _response(503, {"error": {"code": "Unavailable"}}),
        ]
    )
    polling = FoundryDeploymentClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=polling_transport,
        sleeper=lambda _seconds: None,
    )
    with pytest.raises(DeploymentPollError, match="polling failed") as polling_error:
        polling.deploy_prompt(
            agent_name="aiq-001-weather", definition=definition, run_id="poll-error"
        )
    assert polling_error.value.receipt.agent_version == "3"
    assert polling_error.value.receipt.status == "poll_error"


def test_healthy_traffic_concurrency_has_stable_receipt_order() -> None:
    fixtures = load_fixtures(
        ROOT / "agents" / "travel-hosted" / "healthy-traffic.json"
    )
    deployment = DeploymentReceipt(
        "aiq-004-travel",
        "1",
        "hosted_code",
        "sha256:" + ("e" * 64),
        "run",
        "active",
    )

    class StubClient:
        def invoke_hosted(self, receipt, fixture):
            return type("Receipt", (), {"fixture_id": fixture.id})()

    receipts = run_healthy_traffic(StubClient(), deployment, fixtures, max_workers=3)
    assert [receipt.fixture_id for receipt in receipts] == [
        fixture.id for fixture in fixtures
    ]
    with pytest.raises(RuntimeContractError, match="between 1 and 8"):
        run_healthy_traffic(StubClient(), deployment, fixtures, max_workers=0)


def test_version_deployment_uses_version_route_without_create_name() -> None:
    definition = {"kind": "prompt", "model": "test", "instructions": "healthy", "tools": []}
    digest = canonical_json_digest(definition)
    transport = QueueTransport(
        [
            _response(201, {"version": "2"}),
            _response(200, {"status": "active", "metadata": _metadata("run-v2", digest)}),
        ]
    )
    client = FoundryDeploymentClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=transport,
        sleeper=lambda _seconds: None,
    )
    client.deploy_prompt(
        agent_name="aiq-001-weather",
        definition=definition,
        run_id="run-v2",
        create_agent=False,
    )
    assert transport.calls[0]["url"].endswith(
        "/agents/aiq-001-weather/versions?api-version=v1"
    )
    assert "name" not in json.loads(transport.calls[0]["body"])


@pytest.mark.parametrize(
    "endpoint",
    [
        "https://dc.applicationinsights.azure.com/api/projects/fake",
        "https://monitor.azure.com/api/projects/fake",
        "http://sample.services.ai.azure.com/api/projects/quality",
    ],
)
def test_endpoint_adapter_rejects_non_foundry_or_ingestion_routes(endpoint: str) -> None:
    with pytest.raises(RuntimeContractError, match="Foundry project endpoint"):
        FoundryInvocationClient(endpoint, lambda: "token", transport=QueueTransport([]))


def _prompt_receipt(version: str = "42") -> DeploymentReceipt:
    return DeploymentReceipt(
        "aiq-007-scenario",
        version,
        "prompt",
        "sha256:" + ("7" * 64),
        "run-sc",
        "active",
    )


def test_scenario_operations_uses_ordered_results_sleeps_delays_and_records_calls() -> None:
    """Happy path: two ops across two tool turns; configured results returned in order; delays slept."""
    slept: list[float] = []
    ops = (
        SyntheticToolOperation(tool_name="search", result={"hits": 3}, delay_seconds=0.05),
        SyntheticToolOperation(tool_name="fetch", result={"body": "hello"}, delay_seconds=0.0),
    )
    fixture = HealthyFixture(
        id="sc-happy",
        input="go",
        output_contains="done",
        tool_outputs={},
        expected_tool_calls=("search", "fetch"),
        scenario_operations=ops,
    )
    transport = QueueTransport(
        [
            # Turn 1: agent calls "search"
            _response(
                200,
                {
                    "id": "r1",
                    "status": "in_progress",
                    "output": [
                        {"type": "function_call", "call_id": "c1", "name": "search", "arguments": "{}"}
                    ],
                },
            ),
            # Turn 2: agent calls "fetch"
            _response(
                200,
                {
                    "id": "r2",
                    "status": "in_progress",
                    "output": [
                        {"type": "function_call", "call_id": "c2", "name": "fetch", "arguments": "{}"}
                    ],
                },
            ),
            # Final: no more tool calls
            _response(
                200,
                {
                    "id": "r3",
                    "invocation_id": "inv-sc",
                    "status": "completed",
                    "output_text": "done",
                },
                headers={"x-ms-request-id": "req-sc"},
            ),
        ]
    )
    client = FoundryInvocationClient(
        PROJECT_ENDPOINT,
        lambda: "token",
        transport=transport,
        sleeper=slept.append,
    )
    receipt = client.invoke_prompt(_prompt_receipt(), fixture)

    assert receipt.called_tools == ("search", "fetch")
    assert receipt.response_id == "r3"
    assert receipt.invocation_id == "inv-sc"
    assert receipt.request_id == "req-sc"
    # Only the operation with delay_seconds > 0 should have triggered a sleep
    assert slept == [0.05]
    # Verify outputs sent back to the agent carried the configured results
    turn1_body = json.loads(transport.calls[1]["body"])
    assert turn1_body["input"][0]["output"] == '{"hits":3}'
    turn2_body = json.loads(transport.calls[2]["body"])
    assert turn2_body["input"][0]["output"] == '{"body":"hello"}'


def test_scenario_operations_fails_on_wrong_tool_name() -> None:
    """Agent calling a different tool than the configured operation is a contract error."""
    ops = (SyntheticToolOperation(tool_name="expected_tool", result={}),)
    fixture = HealthyFixture(
        id="sc-wrong-name",
        input="go",
        output_contains="unused",
        tool_outputs={},
        expected_tool_calls=("expected_tool",),
        scenario_operations=ops,
    )
    transport = QueueTransport(
        [
            _response(
                200,
                {
                    "id": "r1",
                    "status": "in_progress",
                    "output": [
                        {"type": "function_call", "call_id": "c1", "name": "wrong_tool", "arguments": "{}"}
                    ],
                },
            ),
        ]
    )
    client = FoundryInvocationClient(PROJECT_ENDPOINT, lambda: "token", transport=transport)
    with pytest.raises(RuntimeContractError, match="sequence mismatch"):
        client.invoke_prompt(_prompt_receipt(), fixture)


def test_scenario_operations_fails_when_agent_makes_extra_tool_calls() -> None:
    """Agent calling more tools than configured operations is a contract error."""
    ops = (SyntheticToolOperation(tool_name="tool_a", result={"v": 1}),)
    fixture = HealthyFixture(
        id="sc-extra",
        input="go",
        output_contains="unused",
        tool_outputs={},
        expected_tool_calls=("tool_a",),
        scenario_operations=ops,
    )
    transport = QueueTransport(
        [
            # Turn 1: agent calls tool_a (consumes op 0)
            _response(
                200,
                {
                    "id": "r1",
                    "status": "in_progress",
                    "output": [
                        {"type": "function_call", "call_id": "c1", "name": "tool_a", "arguments": "{}"}
                    ],
                },
            ),
            # Turn 2: agent calls another tool but no operations left
            _response(
                200,
                {
                    "id": "r2",
                    "status": "in_progress",
                    "output": [
                        {"type": "function_call", "call_id": "c2", "name": "tool_b", "arguments": "{}"}
                    ],
                },
            ),
        ]
    )
    client = FoundryInvocationClient(PROJECT_ENDPOINT, lambda: "token", transport=transport)
    with pytest.raises(RuntimeContractError, match="more tool calls than configured"):
        client.invoke_prompt(_prompt_receipt(), fixture)


def test_scenario_operations_fails_when_not_all_operations_consumed() -> None:
    """Agent finishing with unconsumed operations remaining is a contract error."""
    ops = (
        SyntheticToolOperation(tool_name="step_1", result={"ok": True}),
        SyntheticToolOperation(tool_name="step_2", result={"ok": True}),
    )
    fixture = HealthyFixture(
        id="sc-partial",
        input="go",
        output_contains="partial",
        tool_outputs={},
        expected_tool_calls=("step_1", "step_2"),
        scenario_operations=ops,
    )
    transport = QueueTransport(
        [
            # Turn 1: agent calls step_1 (consumes op 0)
            _response(
                200,
                {
                    "id": "r1",
                    "status": "in_progress",
                    "output": [
                        {"type": "function_call", "call_id": "c1", "name": "step_1", "arguments": "{}"}
                    ],
                },
            ),
            # Agent finishes without calling step_2
            _response(
                200,
                {
                    "id": "r2",
                    "status": "completed",
                    "output_text": "partial",
                },
            ),
        ]
    )
    client = FoundryInvocationClient(PROJECT_ENDPOINT, lambda: "token", transport=transport)
    with pytest.raises(RuntimeContractError, match="fewer tool calls than configured"):
        client.invoke_prompt(_prompt_receipt(), fixture)


# ---------------------------------------------------------------------------
# endpoint_request / set_case mutation semantics
# ---------------------------------------------------------------------------


def test_unhealthy_endpoint_case_embeds_case_result_in_request_body_and_ignores_result_field() -> None:
    """Unhealthy cases produce the catalog definition in the function_call_output body."""
    case = "guardrail-bypass-probe"
    expected_case_def = _ENDPOINT_CASES[case]
    assert case not in _ENDPOINT_HEALTHY_CASES

    ops = (SyntheticToolOperation(tool_name="check", result={"ignored": True}, endpoint_case=case),)
    fixture = HealthyFixture(
        id="ec-unhealthy",
        input="probe",
        output_contains="guardrail",
        tool_outputs={},
        expected_tool_calls=("check",),
        scenario_operations=ops,
        expected_final_status="guardrail_triggered",
        validate_output=False,
    )
    transport = QueueTransport(
        [
            _response(
                200,
                {
                    "id": "r1",
                    "status": "in_progress",
                    "output": [
                        {"type": "function_call", "call_id": "c1", "name": "check", "arguments": "{}"}
                    ],
                },
            ),
            # Model returns the case status as the final response status
            _response(
                200,
                {
                    "id": "r2",
                    "invocation_id": "inv-ec",
                    "status": "guardrail_triggered",
                    "output_text": "",
                },
            ),
        ]
    )
    client = FoundryInvocationClient(PROJECT_ENDPOINT, lambda: "token", transport=transport)
    receipt = client.invoke_prompt(_prompt_receipt(), fixture)

    # The function_call_output sent to the model must carry the case definition
    second_body = json.loads(transport.calls[1]["body"])
    embedded_output = json.loads(second_body["input"][0]["output"])
    assert embedded_output == expected_case_def

    # result field ("ignored": True) must NOT appear in the embedded output
    assert "ignored" not in embedded_output

    assert receipt.called_tools == ("check",)
    assert receipt.invocation_id == "inv-ec"


def test_healthy_endpoint_case_wraps_dispatch_result_with_case_metadata() -> None:
    """Healthy cases wrap the configured result with case metadata in the request body."""
    case = "handled-child-failure"
    assert case in _ENDPOINT_HEALTHY_CASES

    dispatch_result = {"balance": 500}
    ops = (SyntheticToolOperation(tool_name="get_balance", result=dispatch_result, endpoint_case=case),)
    fixture = HealthyFixture(
        id="ec-healthy",
        input="check-balance",
        output_contains="done",
        tool_outputs={},
        expected_tool_calls=("get_balance",),
        scenario_operations=ops,
    )
    transport = QueueTransport(
        [
            _response(
                200,
                {
                    "id": "r1",
                    "status": "in_progress",
                    "output": [
                        {"type": "function_call", "call_id": "c1", "name": "get_balance", "arguments": "{}"}
                    ],
                },
            ),
            _response(
                200,
                {
                    "id": "r2",
                    "status": "completed",
                    "output_text": "done",
                },
            ),
        ]
    )
    client = FoundryInvocationClient(PROJECT_ENDPOINT, lambda: "token", transport=transport)
    receipt = client.invoke_prompt(_prompt_receipt(), fixture)

    second_body = json.loads(transport.calls[1]["body"])
    embedded_output = json.loads(second_body["input"][0]["output"])

    # Must contain the case metadata fields
    case_def = _ENDPOINT_CASES[case]
    for key, value in case_def.items():
        assert embedded_output[key] == value

    # Must ALSO contain a dispatch_result key wrapping the configured result
    assert "dispatch_result" in embedded_output
    assert json.loads(embedded_output["dispatch_result"]) == dispatch_result

    assert receipt.called_tools == ("get_balance",)


def test_endpoint_case_with_non_default_expected_final_status_does_not_raise() -> None:
    """expected_final_status lets fixtures declare non-completed terminal status without error."""
    ops = (
        SyntheticToolOperation(
            tool_name="tx",
            result={},
            endpoint_case="no-confirmation",
        ),
    )
    fixture = HealthyFixture(
        id="ec-status",
        input="go",
        output_contains="",
        tool_outputs={},
        expected_tool_calls=("tx",),
        scenario_operations=ops,
        expected_final_status="action_without_confirmation",
        validate_output=False,
    )
    transport = QueueTransport(
        [
            _response(
                200,
                {
                    "id": "r1",
                    "status": "in_progress",
                    "output": [{"type": "function_call", "call_id": "c1", "name": "tx", "arguments": "{}"}],
                },
            ),
            _response(200, {"id": "r2", "status": "action_without_confirmation", "output_text": ""}),
        ]
    )
    client = FoundryInvocationClient(PROJECT_ENDPOINT, lambda: "token", transport=transport)
    # Must NOT raise; status matches expected_final_status
    receipt = client.invoke_prompt(_prompt_receipt(), fixture)
    assert receipt.response_id == "r2"


def test_unknown_endpoint_case_raises_contract_error() -> None:
    """Supplying an unreviewed endpoint_case value is a contract error."""
    ops = (SyntheticToolOperation(tool_name="t", result={}, endpoint_case="not-a-real-case"),)
    fixture = HealthyFixture(
        id="ec-unknown",
        input="go",
        output_contains="unused",
        tool_outputs={},
        expected_tool_calls=("t",),
        scenario_operations=ops,
    )
    transport = QueueTransport(
        [
            _response(
                200,
                {
                    "id": "r1",
                    "status": "in_progress",
                    "output": [{"type": "function_call", "call_id": "c1", "name": "t", "arguments": "{}"}],
                },
            ),
        ]
    )
    client = FoundryInvocationClient(PROJECT_ENDPOINT, lambda: "token", transport=transport)
    with pytest.raises(RuntimeContractError, match="Unknown endpoint_case"):
        client.invoke_prompt(_prompt_receipt(), fixture)
