from __future__ import annotations

from pathlib import Path
from typing import Any
from collections import Counter

from agent_insights_quality.contracts import (
    ContractError,
    ROOT,
    load_agent_manifests,
    load_data,
    load_scenario_catalog,
    load_selection_policy,
)
from agent_insights_quality.memory import render_memory_markdown


GENERATED_NOTICE = "<!-- Generated by `python -m agent_insights_quality generate-docs`; do not edit. -->"


def _agent_doc(agents: list[dict[str, Any]]) -> str:
    lines = [
        "# Test Agents",
        "",
        GENERATED_NOTICE,
        "",
        "All test traffic must invoke the deployed agent endpoint. Application Insights is read-only,",
        "and direct trace injection is forbidden.",
        "",
        "| Stable ID / required prefix | Domain | Type | Status | Healthy responsibility |",
        "| --- | --- | --- | --- | --- |",
    ]
    for agent in agents:
        lines.append(
            f"| `{agent['id']}` | {agent['domain']} | `{agent['agent_type']}` | "
            f"{agent['status']} | {agent['healthy_contract']['responsibility']} |"
        )
    lines.extend(
        [
            "",
            "Agent manifests under `agents/` are authoritative. Healthy baselines are immutable, use",
            "synthetic data only, and must produce zero insights before activation.",
            "",
        ]
    )
    return "\n".join(lines)


def _scenario_doc(catalog: dict[str, Any]) -> str:
    active = [scenario for scenario in catalog["scenarios"] if scenario["status"] == "active"]
    families = Counter(scenario["family"] for scenario in active)
    categories = Counter(scenario["expected"]["category"] for scenario in active)
    severities = Counter(scenario["expected"]["severity"] for scenario in active)
    lines = [
        "# Scenario Catalog",
        "",
        GENERATED_NOTICE,
        "",
        f"Catalog version: `{catalog['catalog_version']}`",
        "",
        (
            f"Active scenarios: **{len(active)}**; families: **{len(families)}**; "
            f"healthy controls: **{categories['none']}**."
        ),
        "",
        "This is the predefined, human-reviewed issue library. The default weekday plan runs all",
        "healthy controls, nine single-root P0 faults, the umbrella P0 probe on Monday/Wednesday/",
        "Friday, and one deterministic five-business-day partition of P1/P2 faults.",
        "",
        "Category coverage: "
        + ", ".join(f"`{name}` ({count})" for name, count in sorted(categories.items())),
        "",
        "Severity coverage: "
        + ", ".join(f"`{name}` ({count})" for name, count in sorted(severities.items())),
        "",
        "## Scenarios",
        "",
        "| Scenario | Version | Family | Priority | Category | Severity | Mutation / traffic recipe | Compatible types |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for scenario in catalog["scenarios"]:
        types = ", ".join(f"`{value}`" for value in scenario["compatibility"]["agent_types"])
        mutation = scenario["mutation"]["recipe_id"] or "none"
        lines.append(
            f"| `{scenario['id']}` - {scenario['title']} | `{scenario['version']}` | "
            f"`{scenario['family']}` | {scenario['priority']} | "
            f"`{scenario['expected']['category']}` | `{scenario['expected']['severity']}` | "
            f"`{mutation}` / `{scenario['traffic']['recipe_id']}` | {types} |"
        )
    lines.extend(["", "## Family coverage", "", "| Family | Active scenarios |", "| --- | ---: |"])
    for family, count in sorted(families.items()):
        lines.append(f"| `{family}` | {count} |")
    lines.extend(
        [
            "",
            "Each source entry fixes its mutation delta, deterministic endpoint traffic recipe, expected",
            "evidence, healthy decoys, negative controls, category, severity, validation targets,",
            "recurrence behavior, compatibility, conflict tags, and version semantics. Ground-truth",
            "changes require human review.",
            "",
        ]
    )
    return "\n".join(lines)


def _issue_library_doc(
    catalog: dict[str, Any],
    policy: dict[str, Any],
) -> str:
    active = [scenario for scenario in catalog["scenarios"] if scenario["status"] == "active"]
    grouped: dict[str, list[dict[str, Any]]] = {}
    for scenario in active:
        grouped.setdefault(scenario["expected"]["category"], []).append(scenario)
    lines = [
        "# Issue Library",
        "",
        GENERATED_NOTICE,
        "",
        "This file lists every predefined, reviewed scenario contract. Daily assignment is a",
        "deterministic weekday subset governed by `config/selection-policy.yaml`; omission from one",
        "day is reviewed cadence or rotation, not retirement or a change to ground truth.",
        "",
        f"Active contracts: **{len(active)}** across **{len(grouped)}** categories.",
        "",
        "| Category | Contracts |",
        "| --- | ---: |",
    ]
    for category, scenarios in sorted(grouped.items()):
        lines.append(f"| `{category}` | {len(scenarios)} |")
    for category, scenarios in sorted(grouped.items()):
        lines.extend(
            [
                "",
                f"## {category}",
                "",
                "| Scenario | Priority | Daily cadence | Expected roots | Root-cause contract | Fix boundary |",
                "| --- | --- | --- | ---: | --- | --- |",
            ]
        )
        for scenario in sorted(scenarios, key=lambda item: item["id"]):
            expected = scenario["expected"]
            if expected["category"] == "none":
                cadence = "Every weekday"
            elif scenario["id"] in policy["selection"]["scenario_cadence"]:
                cadence = "/".join(
                    policy["selection"]["scenario_cadence"][scenario["id"]]
                )
            elif scenario["priority"] == "P0":
                cadence = "Every weekday"
            else:
                cadence = "Once per Monday-Friday cycle"
            lines.append(
                f"| `{scenario['id']}` - {scenario['title']} | {scenario['priority']} | "
                f"{cadence} | {expected.get('finding_count', int(category != 'none'))} | "
                f"{expected['root_cause']} | {expected['fix']['boundary']} |"
            )
    lines.append("")
    return "\n".join(lines)


def generated_documents() -> dict[Path, str]:
    agents = load_agent_manifests()
    catalog = load_scenario_catalog({agent["id"] for agent in agents})
    policy = load_selection_policy(catalog)
    memory = load_data(ROOT / "state" / "quality-memory.json")
    return {
        ROOT / "docs" / "TEST_AGENTS.md": _agent_doc(agents),
        ROOT / "docs" / "SCENARIO_CATALOG.md": _scenario_doc(catalog),
        ROOT / "docs" / "ISSUE_LIBRARY.md": _issue_library_doc(catalog, policy),
        ROOT / "state" / "QUALITY_MEMORY.md": render_memory_markdown(memory),
    }


def generate_documents(check: bool = False) -> None:
    stale = []
    for path, content in generated_documents().items():
        expected = content.encode("ascii")
        actual = path.read_bytes() if path.exists() else None
        if actual == expected:
            continue
        if check:
            stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected)
    if stale:
        raise ContractError(
            "Generated documentation is stale; run `python -m agent_insights_quality generate-docs`:\n"
            + "\n".join(f"- {path}" for path in stale)
        )
