from __future__ import annotations

from pathlib import Path
from typing import Any

from agent_insights_quality.contracts import (
    ContractError,
    ROOT,
    load_agent_manifests,
    load_data,
    load_scenario_catalog,
)


GENERATED_NOTICE = "<!-- Generated by `python -m agent_insights_quality generate-docs`; do not edit. -->"


def _agent_doc(agents: list[dict[str, Any]]) -> str:
    lines = [
        "# Test Agents",
        "",
        GENERATED_NOTICE,
        "",
        "All test traffic must invoke the deployed agent endpoint. Application Insights is read-only,",
        "and direct trace injection is forbidden.",
        "",
        "| Stable ID / required prefix | Domain | Type | Status | Healthy responsibility |",
        "| --- | --- | --- | --- | --- |",
    ]
    for agent in agents:
        lines.append(
            f"| `{agent['id']}` | {agent['domain']} | `{agent['agent_type']}` | "
            f"{agent['status']} | {agent['healthy_contract']['responsibility']} |"
        )
    lines.extend(
        [
            "",
            "Agent manifests under `agents/` are authoritative. Healthy baselines are immutable, use",
            "synthetic data only, and must produce zero insights before activation.",
            "",
        ]
    )
    return "\n".join(lines)


def _scenario_doc(catalog: dict[str, Any]) -> str:
    lines = [
        "# Scenario Catalog",
        "",
        GENERATED_NOTICE,
        "",
        f"Catalog version: `{catalog['catalog_version']}`",
        "",
        "| Scenario | Version | Status | Priority | Category | Severity | Compatible types | Conflicts |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for scenario in catalog["scenarios"]:
        types = ", ".join(f"`{value}`" for value in scenario["compatibility"]["agent_types"])
        conflicts = ", ".join(f"`{value}`" for value in scenario["conflict_tags"]) or "None"
        lines.append(
            f"| `{scenario['id']}` - {scenario['title']} | `{scenario['version']}` | "
            f"{scenario['status']} | {scenario['priority']} | `{scenario['expected']['category']}` | "
            f"`{scenario['expected']['severity']}` | {types} | {conflicts} |"
        )
    lines.extend(
        [
            "",
            "Each source entry fixes its mutation delta, deterministic endpoint traffic recipe, expected",
            "evidence, negative controls, category, severity, fix boundary, compatibility, conflict tags,",
            "and version semantics. Ground-truth changes require human review.",
            "",
        ]
    )
    return "\n".join(lines)


def _memory_doc(memory: dict[str, Any]) -> str:
    lines = [
        "# Quality Memory",
        "",
        GENERATED_NOTICE,
        "",
        f"Last updated: `{memory['updated_at'] or 'never'}`",
        "",
    ]
    if not memory["issues"]:
        lines.extend(["No quality issues have been recorded.", ""])
        return "\n".join(lines)
    lines.extend(
        [
            "| Fingerprint | State | Title | First seen | Last seen | Occurrences | Clean runs | ADO |",
            "| --- | --- | --- | --- | --- | ---: | ---: | --- |",
        ]
    )
    for issue in memory["issues"]:
        ado = issue["ado"]["work_item_reference"] or "N/A"
        lines.append(
            f"| `{issue['fingerprint']}` | {issue['state']} | {issue['title']} | "
            f"{issue['first_seen']} | {issue['last_seen']} | {issue['occurrence_count']} | "
            f"{issue['consecutive_clean_complete_runs']} | {ado} |"
        )
    lines.append("")
    return "\n".join(lines)


def generated_documents() -> dict[Path, str]:
    agents = load_agent_manifests()
    catalog = load_scenario_catalog({agent["id"] for agent in agents})
    memory = load_data(ROOT / "state" / "quality-memory.json")
    return {
        ROOT / "docs" / "TEST_AGENTS.md": _agent_doc(agents),
        ROOT / "docs" / "SCENARIO_CATALOG.md": _scenario_doc(catalog),
        ROOT / "state" / "QUALITY_MEMORY.md": _memory_doc(memory),
    }


def generate_documents(check: bool = False) -> None:
    stale = []
    for path, content in generated_documents().items():
        expected = content.encode("ascii")
        actual = path.read_bytes() if path.exists() else None
        if actual == expected:
            continue
        if check:
            stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected)
    if stale:
        raise ContractError(
            "Generated documentation is stale; run `python -m agent_insights_quality generate-docs`:\n"
            + "\n".join(f"- {path}" for path in stale)
        )
